name: CI
on:
  push:
    branches:
      - main
      - develop
      - feat/*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    runs-on: ubuntu-latest
    outputs:
      publish: ${{steps.check_tag.outputs.tags}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: asnowc/actions@setup-node/v2
        with:
          node_v: 20
          pnpm_v: 8
          run_install: true
      - name: Unit test
        run: pnpm ci:test
      - name: Build
        if: ${{ github.ref_name=='main'}}
        run: pnpm ci:build

      - name: Check API
        if: ${{ github.ref_name=='main' }}
        run: pnpm ci:api-extractor

      - name: Check Tag
        id: check_tag
        uses: asnowc/actions@check-tags/v1
        with:
          file: package.json
  publish:
    needs: build
    if: ${{needs.build.outputs.publish&&github.ref_name=='main'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: Build
        if: ${{ github.ref_name=='main'}}
        run: pnpm ci:build
      - name: Gen Dts
        if: ${{ github.ref_name=='main' }}
        run: pnpm ci:gen-dts

      - name: Setup Deno
        if: ${{ github.ref_name=='main'}}
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Publish
        uses: asnowc/actions@deno-script/v1
        with:
          script: |
            import { tagsPublishFlow } from "https://cdn.jsdelivr.net/gh/dnpack/action-script@0.3.x/cmd/github_repo.ts";
            import { execCmdSync } from "https://cdn.jsdelivr.net/gh/dnpack/action-script@0.3.x/lib.ts";

            await tagsPublishFlow("NEW_TAGS", () => execCmdSync("npm", ["publish"], { exitIfFail: true }));
          args: -A --no-lock
        env:
          NEW_TAGS: ${{needs.build.outputs.publish}}
          GITHUB_TOKEN: ${{secrets.CI_GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
