name: CI
on:
  push:
    branches:
      - main
      - feat/*
      - test/*
jobs:
  build:
    strategy:
      matrix:
        node-version: [18, 20, 22]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: asnowc/actions@setup-node/v2
        with:
          node_v: ${{matrix.node-version}}
          pnpm_v: 9
          run_install: true
      - name: Test
        run: pnpm ci:test

      - name: Build
        if: ${{github.ref_name == 'main' && matrix.node-version == 22}}
        run: pnpm run ci:build
      - name: Check Api
        if: ${{github.ref_name == 'main' && matrix.node-version == 22}}
        run: pnpm run ci:check-api
