name: publish npm
on:
    workflow_dispatch:
        inputs:
            tags:
                description: beta or release
                required: false
                default: latest
                type: string

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: asnow-c/template@v1
              with:
                  nodev: 20
                  pnpmv: 8
                  run_install: true
            - name: build
              run: pnpm build
            - name: publish
              run: npm publish --tag ${{ inputs.tags }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
